Sweave2rmd: BiobaseDevelopment.Rnw to Rmd
Bioconductor/Biobase pull request #16
Opened 2022-10-13 05:57 UTC by hsadia538

Part of Sweave2rmd project.

- Creates a vignette in R markdown for BiobaseDevelopment.Rnw file which replaces the sweave vignette.
- Fix spelling errors

Sample vignettes are attached below:

[BiobaseDevelopment Rmd File](https://github.com/Bioconductor/Biobase/files/9771211/Biobase.development.and.the.new.eSet.html.zip)
[BiobaseDevelopment Rnw File](https://bioconductor.org/packages/release/bioc/vignettes/Biobase/inst/doc/BiobaseDevelopment.pdf)

2022-10-13 05:58 UTC, hsadia538 commented
Hi @jwokaty, Can you please take a look? 
Let me know incase changes are needed.Thanks

2022-10-19 16:38 UTC, jwokaty commented
@mcarlsn Can you do the initial review?

2022-10-20 21:17 UTC, mcarlsn requested changes
Wonderful work on this conversion @hsadia538. 👏🏻👏🏻 I left a few comments for small changes/ edits. @jwokaty FYI there is something interesting going on with the syntax in this vignette (not because of anything you did, hsadia538!). The code runs fine when I go chunk by chunk, but it runs into errors aplenty when knitted. All errors seem tied to `eSet` and `SwirlSet` & the error messages are all variations of "Error in getClass("eSet") : "eSet" is not a defined class". These are the following lines that produce errors when knitted: 
- 65
- 211
- 269 
- 289-290
- 343 
- 399-404
- 421-445
- 451
- 461
- 471-475
- 483-485
- 489
Any ideas? I'm going to keep playing w/ it. Thanks again, @hsadia538!

2022-10-20 21:17 UTC, mcarlsn commented on vignettes/BiobaseDevelopment.Rmd
> +author: R. Gentleman, V. Carey, M. Morgan, S. Falcon
The author line in this file and the vignette PDF don't quite match up. In the PDF, the author is Martin T. Morgan. Please update the author line to match the PDF (see link: https://bioconductor.org/packages/devel/bioc/vignettes/Biobase/inst/doc/BiobaseDevelopment.pdf)

2022-10-20 21:17 UTC, mcarlsn commented on vignettes/BiobaseDevelopment.Rmd
> +-   In Biobase version 2.11 the *MIAxE* virtual class was introduced as a general container for experiment meta-data. The *MIAME* class is now a subclass of *MIAxE*. See `?"MIAxE-class"`. The *MIAME*
Small edit here: in the PDF, this blurb does not have a bullet point. Please remove the bullet point dash. Bullet point list will start again at "title: experiment title."

2022-10-20 21:17 UTC, mcarlsn commented on vignettes/BiobaseDevelopment.Rmd
> +-   `preprocessing`: `list` of pre-processing steps.
Another small edit: `preprocessing` : `list` should be a joined line of code instead of separate syntax words separated by a colon. Please change to `preprocessing: list` like so: 
<img width="148" alt="Screen Shot 2022-10-19 at 4 04 49 PM" src="https://user-images.githubusercontent.com/105299892/196792729-8ff8553b-6bbe-42d6-8b11-d22c6baf3090.png">

2022-10-20 21:17 UTC, mcarlsn commented on vignettes/BiobaseDevelopment.Rmd
> +  %\VignetteIndexEntry{Vignette Title}
Please update "Vignette Title" to "Biobase-BiobaseDevelopment"

2022-10-20 21:17 UTC, mcarlsn commented on vignettes/BiobaseDevelopment.Rmd
> +General programming guidelines emerge from experience with the `initialize` method of `eSet` and derived classes. First, an appropriate strategy is to name only those data elements that will be manip
Small edit: In this passage, you write `R, G, Rb, Rg` but above, in a similar list, you formatted it as `R`, `G`, `Rb`, `Gb`

For the sake of consistency, please select one formatting style and apply it to both lists.

2022-10-20 21:17 UTC, mcarlsn commented on vignettes/BiobaseDevelopment.Rmd
> +```
To better match the formatting in the PDF, please change sessionInfo() to 
<img width="607" alt="Screen Shot 2022-10-20 at 3 59 44 PM" src="https://user-images.githubusercontent.com/105299892/197045982-35e665e6-cd83-4e38-a6eb-a83994815bf8.png">

2022-10-20 21:17 UTC, mcarlsn commented on vignettes/BiobaseDevelopment.Rmd
> +```
Which looks like this when knitted: 
<img width="779" alt="Screen Shot 2022-10-20 at 4 00 18 PM" src="https://user-images.githubusercontent.com/105299892/197046097-d1122c20-37e5-444a-9af6-bc7064ed2b97.png">

2022-10-20 22:10 UTC, hsadia538 commented on vignettes/BiobaseDevelopment.Rmd
> +```
You mean hardcoding the session info here?

2022-10-20 22:13 UTC, hsadia538 commented
>   Any ideas @jwokaty? I'm going to keep playing w/ it. & Thanks again, @hsadia538!

Thank you for the detailed review. I will incorporate the feedback and push changes.

One thing I did before knitting was using `devtools::load_all(".")` at the start which helped me knit and verify the output. I removed it later on as its not part of the code.

2022-10-21 23:01 UTC, hsadia538 commented
@mcarlsn I have pushed changes. Please take a look. thanks

2022-10-22 00:34 UTC, jwokaty commented
@hsadia538 @mcarlsn 

> Wonderful work on this conversion @hsadia538. 👏🏻👏🏻 I left a few comments for small changes/ edits. @jwokaty FYI there is something interesting going on with the syntax in this vignette (not because of anything you did, hsadia538!). The code runs fine when I go chunk by chunk, but it runs into errors aplenty when knitted. All errors seem tied to `eSet` and `SwirlSet` & the error messages are all variations of "Error in getClass("eSet") : "eSet" is not a defined class". These are the following lines that produce errors when knitted:
> 
> * 65
> * 211
> * 269
> * 289-290
> * 343
> * 399-404
> * 421-445
> * 451
> * 461
> * 471-475
> * 483-485
> * 489
>   Any ideas @jwokaty? I'm going to keep playing w/ it. & Thanks again, @hsadia538!

Usually when this happens it means we're missing some code from the original. Typically, we should see a statement loading the package the vignette belongs to with `library()`. In the Rnw, we have https://github.com/Bioconductor/Biobase/blob/6fd3f136c23c8028d6340f5aabddf64dfc6ba809/vignettes/BiobaseDevelopment.Rnw#L100-L103.

So we should add after "# A quick tour"

    ```{r echo=FALSE, message=FALSE}
    options(width=69)
    library(Biobase)
    ```
Then we don't see the errors.

2022-10-24 16:53 UTC, jwokaty commented on vignettes/BiobaseDevelopment.Rmd
> +```
We shouldn't hard code this.

2022-10-24 19:52 UTC, hsadia538 commented on vignettes/BiobaseDevelopment.Rmd
> +```
Should I revert back to `sessionInfo()`

2022-10-25 03:17 UTC, mcarlsn commented on vignettes/BiobaseDevelopment.Rmd
> +```
Apologies for the misdirection @hsadia538! I went back and forth on this edit before commenting - glad to know we should stick to sessionInfo(). Hopefully it wasn't too much of a hassle for you to revert this edit.

2022-10-25 22:42 UTC, hsadia538 commented on vignettes/BiobaseDevelopment.Rmd
> +```
No worries.

2022-10-25 22:45 UTC, hsadia538 commented on vignettes/BiobaseDevelopment.Rmd
> +```
I have updated. Please take a look thanks 🙂

2022-10-28 01:39 UTC, jwokaty requested changes
Thanks for working on this vignette. This is just my way of thinking but maybe we don't need the spaces between each list item since it makes the document long for future vignettes; we'll leave them for this vignette. Can I ask you to make the other changes and re-request a review when they're done?

2022-10-28 01:39 UTC, jwokaty commented on DESCRIPTION
> +Suggests: tools, tkWidgets, ALL, RUnit, golubEsets, BiocStyle, Knitr
Since we already made all the changes for the `DESCRIPTION` file in #17, let's remove this change.

2022-10-28 01:39 UTC, jwokaty commented on vignettes/BiobaseDevelopment.Rmd
> +- name "Martin T. Morgan*"
Let's remove the `*` after `Morgan`. The email that's displayed in the PDF is old, so we don't want to use that.  Also add the `:` after `name`.

2022-10-28 01:39 UTC, jwokaty commented on vignettes/BiobaseDevelopment.Rmd
> +    obj <- new("ExpressionSet", phenoData = new("AnnotatedDataFrame"), experimentData = new("MIAME"), annotation = character(),        exprs = new("matrix"))
Can we format for easier reading:

```
obj <- new(
    "ExpressionSet", 
    phenoData = new("AnnotatedDataFrame"),
    experimentData = new("MIAME"), annotation = character(), 
    exprs = new("matrix")
)
```

2022-10-28 01:39 UTC, jwokaty commented on vignettes/BiobaseDevelopment.Rmd
> +                           ...) )
After the `)` on line 321, we should have a space followed by `{` because it's the start of a function.

The 2nd `)` on 324 should be on the next line with the closing `}` before it--e.g, `})`.

2022-10-28 01:39 UTC, jwokaty commented on vignettes/BiobaseDevelopment.Rmd
> +              }
Let's fix the indent of `warning` and the closing `}`.

2022-10-28 01:39 UTC, jwokaty commented on vignettes/BiobaseDevelopment.Rmd
> +```{r}
I think we need `eval=FALSE` to prevent the code from being run.

2022-10-28 01:39 UTC, jwokaty commented on vignettes/BiobaseDevelopment.Rmd
> +*Biobase* introduces the *Versioned* and *VersionedBiobase* classes to facilitate this. These classes are incorporated into key *Biobase*class definitions.*Biobase* also defines `updateObject` method
Let's make `BiocGenerics` a link to the package with `Biocpkg("BiocGenerics")`

2022-10-28 01:39 UTC, jwokaty commented on vignettes/BiobaseDevelopment.Rmd
> +
Remove extra line 62 and let's remove line 60 `options(width=69)`.

2022-10-28 01:39 UTC, jwokaty commented on vignettes/BiobaseDevelopment.Rmd
> +`> assayDataNew("environment", elt)`
We should use the code block structure for this with `eval=FALSE` so that we can remove the `>`.

2022-10-28 14:16 UTC, hsadia538 commented
> Thanks for working on this vignette. This is just my way of thinking but maybe we don't need the spaces between each list item since it makes the document long for future vignettes; we'll leave them for this vignette. Can I ask you to make the other changes and re-request a review when they're done?

Hi, which list items are you exactly referring to(just for understanding purposes)

2022-10-28 14:30 UTC, hsadia538 commented on vignettes/BiobaseDevelopment.Rmd
> +*Biobase* introduces the *Versioned* and *VersionedBiobase* classes to facilitate this. These classes are incorporated into key *Biobase*class definitions.*Biobase* also defines `updateObject` method
Do you want me to adda hyperlink and link it to package installation page?

2022-10-28 15:05 UTC, jwokaty commented on vignettes/BiobaseDevelopment.Rmd
> +*Biobase* introduces the *Versioned* and *VersionedBiobase* classes to facilitate this. These classes are incorporated into key *Biobase*class definitions.*Biobase* also defines `updateObject` method
Since we're using BiocStyle, the function `Biocpkg()` will make the link for us. (Sorry that wasn't clear!)

2022-10-28 15:10 UTC, jwokaty commented
> > Thanks for working on this vignette. This is just my way of thinking but maybe we don't need the spaces between each list item since it makes the document long for future vignettes; we'll leave them for this vignette. Can I ask you to make the other changes and re-request a review when they're done?
> 
> Hi, which list items are you exactly referring to(just for understanding purposes)

Thanks for asking for clarification. I was referring to lines like 43-55, where there's a blank line after each item in the list. As I mentioned, let's leave them for now.

2022-10-28 15:19 UTC, hsadia538 commented on vignettes/BiobaseDevelopment.Rmd
> +*Biobase* introduces the *Versioned* and *VersionedBiobase* classes to facilitate this. These classes are incorporated into key *Biobase*class definitions.*Biobase* also defines `updateObject` method
Ok got it , thanks
Also one for thing, I have made multiple commits here. Is it okay as is or I should squash them to keep the history clean?

2022-10-28 15:23 UTC, hsadia538 commented on vignettes/BiobaseDevelopment.Rmd
> +*Biobase* introduces the *Versioned* and *VersionedBiobase* classes to facilitate this. These classes are incorporated into key *Biobase*class definitions.*Biobase* also defines `updateObject` method
The function knits as followes:
`(the updateObject generic function is defined in the Biocpkg(“BiocGenerics”) package) for conveniently updating old objects to their new representation.`

Its not turning into a link

2022-10-28 17:27 UTC, jwokaty commented on vignettes/BiobaseDevelopment.Rmd
> +*Biobase* introduces the *Versioned* and *VersionedBiobase* classes to facilitate this. These classes are incorporated into key *Biobase*class definitions.*Biobase* also defines `updateObject` method
I will squash commits when I merge.  For the link, try using `r Biocpkg("BiocGenerics")`. Here's the BiocStyle documentation: https://bioconductor.org/packages/release/bioc/vignettes/BiocStyle/inst/doc/AuthoringRmdVignettes.html#4_Style_macros.

2022-10-28 18:00 UTC, hsadia538 commented on vignettes/BiobaseDevelopment.Rmd
> +*Biobase* introduces the *Versioned* and *VersionedBiobase* classes to facilitate this. These classes are incorporated into key *Biobase*class definitions.*Biobase* also defines `updateObject` method
Done and pushed changes.
Thank you

2022-10-31 18:14 UTC, jwokaty commented on DESCRIPTION
> +Suggests: tools, tkWidgets, ALL, RUnit, golubEsets, BiocStyle, Knitr
We still need the `Suggests` line, but this diff shows that the `k` in `knitr` was capitalized, so we just needed to undo that.

2022-10-31 20:02 UTC, jwokaty approved these changes
I made a few changes to get this ready for merge, but I wanted to mention a few things. The `Suggest` line in DESCRIPTION needed to be added back. `Authors@R`, is a vector of lists, so the commas are important. The remainder of changes were primarily formatting issues to improve code blocks.

2022-10-31 20:04 UTC, merged