Sweave2rmd: Convert esApply.Rnw to .Rmd
Bioconductor/Biobase pull request #17
Opened 2022-10-25 22:35 UTC by hsadia538

Part of Sweave2rmd project.

Previous PR: #15 

Describe Changes:
- Update esApply.Rmd and DESCRIPTION file to incorporate feedback

2022-10-25 22:36 UTC, hsadia538 commented
@jwokaty  I have incorporated the feedback added on last PR. Please take a look . Thanks

2022-10-26 15:01 UTC, jwokaty requested changes
Thanks for this. Two last edits and we'll be good to finish this up.

2022-10-26 15:01 UTC, jwokaty commented on DESCRIPTION
> +    )
At line 18, we should have `),`  and at 23 we need `))` because Authors@R is a vector.

2022-10-26 15:01 UTC, jwokaty commented on vignettes/esApply.Rmd
Remove the extra line before the fence ` ``` `

2022-10-27 13:43 UTC, jwokaty commented
@hsadia538 I'm making these changes because Biobase is a dependency for a lot of packages and it's currently failing because of the error in the DESCRIPTION file. Bioconductor has a release next week, so we want as many packages as possible building.

2022-10-27 13:45 UTC, merged

2022-10-27 21:24 UTC, hsadia538 commented on DESCRIPTION
> +    )
Apologies , I did not realize about the matching brackets

2022-10-27 21:25 UTC, hsadia538 commented
> @hsadia538 I'm making these changes because Biobase is a dependency for a lot of packages and it's currently failing because of the error in the DESCRIPTION file. Bioconductor has a release next week, so we want as many packages as possible building.

Alright, Thanks a lot.
I was caught up at home and couldn't make changes quickly